catalog/urls.py
from django.urls import path
from . import views

app_name = "catalog"
urlpatterns = [
    path("", views.home, name="Home"),
    path("home/portofolio/", views.portofolio, name="Portofolio"),
    path("background/", views.background, name="Background"),
    path("resume/", views.resume, name="Resume"),
    path("contact/", views.contact, name="Contact"),
    path("contactlist/", views.contactlist, name="ContactList"),
    path("video/", views.video, name="Video"),
    path("gallery/", views.gallery, name="Gallery"),
    path("schedule/", views.jadwal, name="Schedule"),
    path ("/delete/<int:items_id>/", views.deleteItems, name="delete"),
]

story_4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

catalog/models.py
from django.db import models

# Create your models here.
class Hasil(models.Model):
    hari = models.CharField(max_length = 10, default="Unknown")
    tanggal = models.DateField(max_length = 10, default="Unknown")
    waktu = models.TimeField(max_length = 10, default="Unknown")
    kegiatan = models.CharField(max_length= 100, default="Unknown")
    lokasi = models.CharField(max_length = 20, default="Unknown")
    kategori = models.CharField(max_length = 20, default="Unknown")

catalog/views.py
from django.shortcuts import render, redirect
from .models import Hasil
from django.core.exceptions import ValidationError

def home(request):
    return render(request, "Home.html")

def portofolio(request):
    return render(request, "Portofolio.html")

def background(request):
    return render(request, "Background.html")

def resume(request):
    return render(request, "Resume.html")

def contact(request):
    return render(request, "Contact.html")

def contactlist(request):
    return render(request, "ContactList.html")

def gallery(request):
    return render(request, "Gallery.html")

def video(request):
    return render(request, "Video.html")

def deleteItems(request, items_id):
    a = Hasil.objects.get(id=items_id)
    a.delete()
    return redirect("catalog:Schedule")

def jadwal(request):
    context = {}
    if request.method == "POST":
        hari = request.POST.get('hari')
        tanggal = request.POST.get('tanggal')
        waktu = request.POST.get('waktu')
        kegiatan = request.POST.get('kegiatan')
        lokasi = request.POST.get('lokasi')
        kategori = request.POST.get('kategori')
        hasil = Hasil(hari=hari, tanggal=tanggal, waktu=waktu, kegiatan=kegiatan, lokasi=lokasi, kategori=kategori)
        try:
            hasil.clean()
            hasil.save()
        except ValidationError:
            pass
    context['hasilan'] = Hasil.objects.all().order_by('tanggal')    
    return render(request, "Jadwal.html", context)

catalog/templates/Background.html
<!DOCTYPE html>
<html lang="en">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
            {% load staticfiles %}
        <link rel="icon" href="{% static 'image/logo.png' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/Background.css' %}"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>
            akbarrafs - Background
        </title>
    </head>
    <body style="position: absolute; width: 100%; height: 100%" class="bodystyle">
        <header>
            <div class="logo">
                <img src="{% static 'image/logo.png' %}">
            </div>
            <nav class="navbar-expand-lg">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Home' %}"> HOME</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Portofolio' %}"> PORTOFOLIO</a></li>
                    <li class="nav-item active"><a class = "nav-link" href = "{% url 'catalog:Background' %}"> BACKGROUND</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Resume' %}"> RESUME</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Contact' %}"> CONTACT</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Schedule' %}"> SCHEDULE</a></li>
                </ul>
            </nav>     
        </header>
        <section class="introbackground">
            <p class="intropengamen">
                "Bang, tolong ajari saya main gitar!"
            </p>
            <p class="introcerita">
                Saya ingat betul ketika saya mengucapkan kalimat
                tersebut. “Oh boleh, tapi yang mengajar adalah<br> anak
                saya, dia juga ngamen kayak saya dek.” Tanpa basa
                - basi, saya setuju dan untungnya bapak <br>saya menyetujuinya.
                Saya ngga ngerti bagaimana bisa saya minta diajarkan main
                gitar dengan seorang<br> pengamen. Mungkin juga karena saya sudah
                terlanjur kagum dengan cara bermain si bapak pengamen.<br>
            </p>
            <p class="introcerita2">
                Sekitar 1-2 minggu (pertemuan 2 x seminggu), 
                saya sudah bisa memainkan kunci C, A, D, E, G<br> dengan lancar. 
                Belajarnya sangat simple, saya hanya diajar bermain lagu - 
                lagu band yang berkunci<br> dasar di C, D, A E, G. Kelemahannya 
                adalah saya tidak dikenalkan apa itu tangga nada dan juga apa<br> 
                itu tablature, sehingga pr nya saya harus belajar sendiri karena 
                beliau tidak mengerti. Tapi dari situ<br> saya juga senang karena tidak 
                merasa harus terbebani bermain gitar dengan target kelulusan atau<br>
                kenaikan tingkat seperti di tempat les pada umumnya. Sekarang, 
                saya bisa mengenal tangga nada dan<br> juga sudah bisa membaca tablature.
                Saya akan terus belajar dan mencari tahu tentang gitar.
            </p>
            <div>
                <img src="{% static 'image/pengamenlagi.jpg' %}">
            </div>
        </section>
        <footer class="bawahankaki">
            <p class="captionbawah">
                © 2019 Akbar Rafsanjhani. All rights reserved.
            </p>
        </footer>
    </body>
</html>

catalog/templates/Contact.html
<!DOCTYPE html>
<html lang="en">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
            {% load staticfiles %}
        <link rel="icon" href="{% static 'image/logo.png' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/Contact.css' %}"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>
            akbarrafs - Contact
        </title>
    </head>
    <body>
        <header>
            <div class="logo">
                <img src="{% static 'image/logo.png' %}">
            </div>
            <nav class="navbar-expand-lg">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Home' %}"> HOME</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Portofolio' %}"> PORTOFOLIO</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Background' %}"> BACKGROUND</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Resume' %}"> RESUME</a></li>
                    <li class="nav-item active"><a class = "nav-link" href = "{% url 'catalog:Contact' %}"> CONTACT</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Schedule' %}"> SCHEDULE</a></li>
                </ul>
            </nav> 
            <p class="captiontengah">
                Feel free to contact me!
            </p>
            <p class="captionbawah">
                <a href = "{% url 'catalog:ContactList' %}">Click Here</a>
            </p>
            <p class="gallery">
                <a href = "{% url 'catalog:Gallery' %}"> Wanna see my gallery?
                </a>
            </p>       
        </header>
        <footer class="bawahankaki">
                <p class="captionbawah">
                    © 2019 Akbar Rafsanjhani. All rights reserved.
                </p>
        </footer>
    </body>
</html>

catalog/templates/ContactList.html
<!DOCTYPE html>
<html lang="en">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
            {% load staticfiles %}
        <link rel="icon" href="{% static 'image/logo.png' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/ContactList.css' %}" />
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" /> -->
        <title>
            akbarrafs - Contact List
        </title>
    </head>
    <section class="webnya">
    <p><a href="{% url 'catalog:Contact' %}">
        X
    </a></p>
    <img class="fesbok" src="{% static 'image/facebook.svg' %}" onclick="window.location.href='https://www.facebook.com/akbarsts';">
    <img class="ig" src="{% static 'image/instagram.svg' %}" onclick="window.location.href='https://www.instagram.com/akbarrafs_/';">
    <img class="yt" src="{% static 'image/youtube.svg' %}" onclick="window.location.href='https://www.youtube.com/channel/UCbp10xq0yJmEK7f2mdCyddg?view_as=subscriber';">
    <img class="meyl" src="{% static 'image/mail.png' %}">
    <img class="twit" src="{% static 'image/twitter.svg' %}" onclick="window.location.href='https://twitter.com/mogearogan';">
    </section>
</html>

catalog/templates/Gallery.html
<!DOCTYPE html>
<html lang="en">
    <head>
            {% load staticfiles %}
        <link rel="icon" href="{% static 'image/logo.png' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/Gallery.css' %}"/>
        <title>
            akbarrafs - Gallery
        </title>
    </head>
    <header>
        <div class="logo">
            <img src="{% static 'image/logo.png' %}">
        </div>
        <nav class="navbar-expand-lg">
            <ul class="navbar-nav">
                <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Home' %}"> HOME</a></li>
                <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Portofolio' %}"> PORTOFOLIO</a></li>
                <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Background' %}"> BACKGROUND</a></li>
                <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Resume' %}"> RESUME</a></li>
                <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Contact' %}"> CONTACT</a></li>
                <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Schedule' %}"> SCHEDULE</a></li>
            </ul>
        </nav> 
    </header>
    <section>
        <div class="container">
            <img class="picture" src="{% static 'image/Dua.jpg' %}">
            <img class="picture" src="{% static 'image/Tiga.jpg' %}">
            <img class="picture" src="{% static 'image/Empat.jpg' %}"> 
        </div>
        <div class="container">
            <img class="picture" src="{% static 'image/Lima.jpg' %}">
            <img class="picture" src="{% static 'image/Enam.jpg' %}">
            <img class="picture" src="{% static 'image/Tujuh.jpg' %}">
        </div>
    </section>
    <footer class="bawahankaki">
            <p class="captionbawah">
                © 2019 Akbar Rafsanjhani. All rights reserved.
            </p>
    </footer>
</html>

catalog/templates/Home.html
<!DOCTYPE html>
<html lang="en">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head> 
            {% load staticfiles %}
        <link rel="icon" href="{% static 'image/logo.png' %}"> 
        <link rel="stylesheet" type="text/css" href="{% static 'css/Home.css' %}" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="{% static 'js/parallax.min.js' %}"></script>
        <title>
            akbarrafs - Home
        </title>
    </head>
    <body>
        <header data-parallax="scroll" data-image-src="{% static 'image/guitaristEdit.JPG' %}">
            <div class="main">
                <div class="logo">
                    <img src="{% static 'image/logo.png' %}">
                </div>
                <nav class="navbar-expand-lg">
                    <ul class="navbar-nav">
                        <li class="nav-item active"><a class = "nav-link" href = "{% url 'catalog:Home' %}"> HOME</a></li>
                        <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Portofolio' %}"> PORTOFOLIO</a></li>
                        <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Background' %}"> BACKGROUND</a></li>
                        <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Resume' %}"> RESUME</a></li>
                        <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Contact' %}"> CONTACT</a></li>
                        <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Schedule' %}"> SCHEDULE</a></li>
                    </ul>
                </nav> 
                <h1 class="captiontengah">
                    "GUITAR IS NOT A THING, GUITAR IS ME"
                </h1>
                <div>
                    <a href = "{% url 'catalog:Portofolio' %}">
                    <button  class="portobutton">
                        See My Portofolio
                    </button>
                    </a>
                </div>
            </div>
        </header>
        <section class="introbackground">
            <div>
            <p class="intropengamen">
                Belajar dari Seorang Pengamen
            </p>
            <p class="introcerita">
                Saya terkagum - kagum dengan pengamen yang bermain musik<br> didepan rumah saya.
                Apalagi   dari   cara  ia menggenjreng <br> gitarnya, sungguh hebat!
                “Bagaimana saya bisa belajar gitar <br>sepertinya?”
            </p>
            <div>
                <a href = "{% url 'catalog:Background' %}">
                    <button class="resumebutton">
                        See My Background
                    </button>
                </a>
            </div>
                <img src="{% static 'image/Pengamen.jpg' %}">
            </div>
            
        </section>
        <footer class="bawahankaki">
            <p class="captionbawah">
                © 2019 Akbar Rafsanjhani. All rights reserved.
            </p>
        </footer>
    </body>
</html>

catalog/templates/Jadwal.html
<!DOCTYPE html>
<html lang="en">
    <head>
            {% load staticfiles %}
        <link rel="icon" href="{% static 'image/logo.png' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/Jadwal.css' %}"/>
        <title>
            akbarrafs - Schedule
        </title>
    </head>
    <body>
        <header>
            <div class="logo">
                <img src="{% static 'image/logo.png' %}">
            </div>
            <nav class="navbar-expand-lg">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Home' %}"> HOME</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Portofolio' %}"> PORTOFOLIO</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Background' %}"> BACKGROUND</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Resume' %}"> RESUME</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Contact' %}"> CONTACT</a></li>
                    <li class="nav-item active"><a class = "nav-link" href = "{% url 'catalog:Schedule' %}"> SCHEDULE</a></li>
                </ul>
            </nav> 
        </header>
            <!-- Modal -->
            <form action="" method="POST">
                {% csrf_token %}
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">
                                    Add Task..
                                </h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span class="bg-white" aria-hidden="true">
                                        &times;
                                    </span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="bg-white">
                                    <input name="hari" type="text" placeholder="Day"><br>
                                    <input name="tanggal" type="date"><br>
                                    <input name="waktu" type="time"><br>
                                    <input name="kegiatan" type="text" placeholder="Task"><br>
                                    <input name="lokasi" type="text" placeholder="Location"><br>
                                    <input name="kategori" type="text" placeholder="Category"><br>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button close" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="button submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
              <div class="container-fluid konten">
                      <div>
                    <a>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                        Add Task!
                    </button>
                    </a>
                </div>
            <div class="notcomp">
                <h3 class="textcuy">
                    Not Completed (Click for done)
                </h3>
                <a>
                    {% for hasil in hasilan %}
                    <form action="{% url 'catalog:delete' hasil.id %}">
                        <button class="tomblo" type="submit" name="delete">
                        {{ hasil.kegiatan  }}<br>
                            {{ hasil.hari }}, {{ hasil.tanggal }}, {{ hasil.waktu }}<br>
                            {{ hasil.lokasi }}<br>
                            {{ hasil.kategori }}<br>
                        </button>
                    </form>
                    {% endfor %}
                </a>
            </div>
        </div>
    </body>
</html>

catalog/templates/Portofolio.html
<!DOCTYPE html>
<html lang="en">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
            {% load staticfiles %}
        <link rel="icon" href="{% static 'image/logo.png' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/Portofolio.css' %}"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>
            akbarrafs - Portofolio
        </title>
    </head>
<body>
    <header>
        <div class="logo">
            <img src="{% static 'image/logo.png' %}">
        </div>
        <nav class="navbar-expand-lg">
            <ul class="navbar-nav">
                <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Home' %}"> HOME</a></li>
                <li class="nav-item active"><a class = "nav-link" href = "{% url 'catalog:Portofolio' %}"> PORTOFOLIO</a></li>
                <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Background' %}"> BACKGROUND</a></li>
                <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Resume' %}"> RESUME</a></li>
                <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Contact' %}"> CONTACT</a></li>
                <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Schedule' %}"> SCHEDULE</a></li>
            </ul>
        </nav>   
    </header>
    <section class="topbackground">
        <div class="phum">
            <a href="{% url 'catalog:Video' %}">
            <img src="{% static 'image/phum.PNG' %}">
            </a>
        </div>
        <p class="phumcaption">
            Me tryin to enjoy my <br> life even i'm not her<br> lover boy.
        </p>
    </section>
    <section class="midbackground">
        <div class="boy">
            <a href = "{% url 'catalog:Video' %}">
            <img src="{% static 'image/boy.PNG' %}">
            </a>
        </div>
        <p class="boycaption">
            Who is prepared <br>to let someone go?
        </p>
    </section>
    <section class="botbackground">
        <div class="paul">
            <a href = "{% url 'catalog:Video' %}">
            <img src="{% static 'image/paul.PNG' %}">
            </a>
        </div>
        <p class="paulcaption">
            Take this broken wings<br> and learn to fly.
        </p>
    </section>
    <footer class="bawahankaki">
        <p class="captionbawah">
            © 2019 Akbar Rafsanjhani. All rights reserved.
        </p>
    </footer>
</body>
</html>

catalog/templates/Resume.html
<!DOCTYPE html>
<html lang="en">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
            {% load staticfiles %}
        <link rel="icon" href="{% static 'image/logo.png' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/Resume.css' %}"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="{% static 'js/parallax.min.js' %}"></script>
        <title>
            akbarrafs - Resume
        </title>
    </head>
    <body>
        <header>
            <div class="logo">
                <img src="{% static 'image/logo.png' %}">
            </div>
            <nav class="navbar-expand-lg">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Home' %}"> HOME</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Portofolio' %}"> PORTOFOLIO</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Background' %}"> BACKGROUND</a></li>
                    <li class="nav-item active"><a class = "nav-link" href = "{% url 'catalog:Resume' %}"> RESUME</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Contact' %}"> CONTACT</a></li>
                    <li class="nav-item"><a class = "nav-link" href = "{% url 'catalog:Schedule' %}"> SCHEDULE</a></li>
                </ul>
            </nav>  
            </div>        
        </header>
        <section class="tutupan">
            <h1 class="turuninbro">
                Click Here!
            </h1>
            <div class="blinker">
                <img src="{% static 'image/ic_arrow_1053005.png' %}" onclick="window.location.href = '#resume';">
            </div>
        </section>
        <section class="grid" id="resume">
            <div class="container-fluid">
                <div class="row pertama">
                    <div class="col-md-6 kirisatu" data-parallax="scroll" data-image-src="{% static 'image/begron_rev4.png' %}">
                        <img class="ganteng" src="{% static 'image/ganteng.png' %}">
                        <p class="experience">
                            Experience
                        </p>
                        <p class="skills">
                            Skills
                        </p>
                        </div>
                    <div class="col-md-6 kanansatu">
                        <p class="aboutmehjudul">
                            About Me
                        </p>
                        <p class="aboutmehisi">
                            Saya adalah seorang mahasiswa FASILKOM UI<br>
                            Semester 3. Saya dipercaya sebagai orang <br>
                            yang cepat mempelajari hal yang saya se-<br>
                            nangi, terutama dalam bermusik. Dengan <br>
                            bermusik, tidak hanya hidup saya yang <br>
                            akan indah, tetapi orang lain pun juga.<br>
                        </p>
                        <img class="senbud" src="{% static 'image/senbud.png' %}">
                        <p class="captionexp2">
                            Staff of BEM Seni Budaya 2019
                        </p>
                        <img class="uiaw" src="{% static 'image/uiaw7Cropped.png' %}">
                        <p class="captionexp">
                            - Equipment Staff UIAW 2018<br>
                            - Film Contingent UIAW 2018
                        </p>
                        <div class="container skillsbar">
                            <div class="bar front advanced" data-skill="Guitar">
                            </div>
                            <div class="bar front intermediate" data-skill="DJ">
                            </div>
                            <div class="bar front intermediate" data-skill="Bass">
                            </div>
                            <div class="bar front learning" data-skill="Keyboard/Piano">
                            </div>
                            <div class="bar front basic" data-skill="Drum">
                            </div>
                            <div class="bar front intermediate" data-skill="Vocal">
                            </div>
                            <div class="bar front basic" data-skill="Adobe Photoshop">
                            </div>
                            <div class="bar front intermediate" data-skill="Adobe Premiere">
                            </div>
                            <div class="bar front intermediate" data-skill="Adobe After Effects">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <footer class="bawahankaki">
            <p class="captionbawah">
                © 2019 Akbar Rafsanjhani. All rights reserved.
            </p>
        </footer>
    </body>
</html>

catalog/templates/Video.html
<!DOCTYPE html>
<html lang="en">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
            {% load staticfiles %}
        <link rel="icon" href="{% static 'image/logo.png' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/Video.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
        <title>
            akbarrafs - Video
        </title>
    </head>
    <section class="video">
    <p><a href="{% url 'catalog:Portofolio' %}">
        X
    </a>
    </p>
    <img src="{% static 'image/play.png' %}">
    </section>
</html>